### PR TITLE
CSS styling for "View Note in AnkiHub"

### PR DESCRIPTION
**Pull request by cafelinked**
Added CSS styling for "View Note in AnkiHub" and changed position to bottom right. See image.

image

### CODE REVIEW

**Comment by cafelinked** [comment]
Added code in /src/ and /NoteTypes/.
Fixed Anki Hyperlink image overlap with View Note in AnkiHub. 

Should be all good to go, if you choose to accept these changes. (:

**Comment by AnKingMed** [comment]
@cafelinked thanks for doing this. @RisingOrange do you think we should make something in the note types for configuring the AnKing note type and add it to the add-on? This seems to be a frequent suggestion recently. Could perhaps have a drop down with a few styles?

**Comment by AnKingMed** [comment]
@cafelinked I'm not sure I love the bottom right or left because on mobile that's right where you may be tapping. What's been your experience with your style?

**Comment by cafelinked** [comment]
@AnKingMed Glad you brought that up. Styling for the mobile seems to vary between iOS & Android. On Android (tablet), it seems to be exactly where it should be at, bottom right. However, on iOS there it is showing in center right. See images. 

We could eliminate this on mobile completely with the following:
`.mobile a {
	display: none;
}`

That would solve this issue entirely and for the moment while we test various locations along with various styles. 
As far as designs go, feel free to experiment based on everyone's liking. We could stick with the hint-button colors/style if desired to keep it all uniform. I went with the color, since my decks are mainly UWorld color replica. And rounded design from base Anki new UI which have a slightly rounded buttons. The drop-down menu with few styles would be nice, though I am not too deep into the coding yet, still scratching the surface. lol. But I am sure people would love to implement various designs (perhaps import this within the NoteTypes menu?). 

iOS:
Image 0
Android:
Screenshot_20230305_193817_AnkiDroid
Screenshot_20230305_193832_AnkiDroid

**Comment by AnKingMed** [comment]
The one on android seems reasonable, but I don't love where it's at on iOS. I don't really want to remove it completely (I personally use it quite often on mobile).  I'll chat with our AnkiHub team and see if we can come up with a solution. @RisingOrange is very familiar with the note types and the note types add-on so we can do something once he has time. It may be better to implement this from AnkiHub?

**Comment by RisingOrange** [comment]
> do you think we should make something in the note types for configuring the AnKing note type and add it to the add-on? This seems to be a frequent suggestion recently. Could perhaps have a drop down with a few styles?

We can do that. 

> It may be better to implement this from AnkiHub?

 I think it's easier to let people choose the option using the AnKing note types add-on for now rather than using the AnkiHub add-on.

Do you have any ideas about which style options we should provide?

**Comment by cafelinked** [comment]
@RisingOrange I've been experimenting with `@media screen` but I am unable to resolve the issue on iOS. I'd love to see how you implement this! Looking forward to seeing your work. HTML, CSS, and Python seems relatively straight forward to learn, been doing it on my down time last few months (:

> Do you have any ideas about which style options we should provide?

Bringing it back to the issue, if the issue on iOS is continuing to persists, could we implement the entire thing as a Hint Button Style? That way, it stays at the end of however many hint buttons are shown to the user, and is position is relative. (if 4 fields, View Note Hint Button is shown as the 5th Hint Button, and so on). 

> I think it's easier to let people choose the option using the AnKing note types add-on for now rather than using the AnkiHub add-on.

I do feel it would be easier to use the AnkiHub add-on. I was able to come up with this pull-request primarily due to how my FACK'23 was showing up when I started the collaboration with AnkiHub. The "View Note in AnkiHub" overlays the images and texts. And hence, this styling idea was brought to light. So adjusting this from the source end can resolve the issue, and the implemented on Note-Types for those who do not use AnkiHub. See image for example. Link to the problem on [AnkiHub](https://community.ankihub.net/t/view-note-in-ankihub-styling-not-aligning-with-images-on-fields/1060). Image Attached. 
8704762acd345326035a01abfa94a7790669413d

**Comment by AnKingMed** [comment]
> Do you have any ideas about which style options we should provide?
@RisingOrange I'm not 100% sure. We could poll on community.AnkiHub.net.  My thoughts:
1. Current style at bottom of note (I actually like it in the button style @cafelinked is suggesting here)
2. bottom right
3. bottom left
4. under a toggleable button like the AnKing notes have (this may be ideal for mobile so it's less accidentally triggered?)

**Comment by AnKingMed** [comment]
@cafelinked quick update - they're going to update things on the AnkiHub side so that it works for everyone and not just those with anking note types so I'm going to close this but you can reach out with ideas on community.AnkiHub.net

**Pull request closed without merging**
